apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
  namespace: monitoring
data:
  dashboard-app-requests.json: |
    {
      "annotations": { "list": [] },
      "panels": [
        {
          "datasource": "Prometheus",
          "type": "graph",
          "title": "App requests (rate)",
          "targets": [
            {
              "expr": "rate(app_requests_total[1m])",
              "format": "time_series"
            }
          ],
          "id": 1,
          "gridPos": {"h": 8, "w": 24, "x": 0, "y": 0}
        },
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "Total requests",
          "targets": [
            {
              "expr": "sum(app_requests_total)",
              "format": "time_series"
            }
          ],
          "id": 2,
          "gridPos": {"h": 4, "w": 12, "x": 0, "y": 8}
        }
      ],
      "schemaVersion": 16,
      "title": "App Metrics",
      "version": 1
    }
